spring:
  datasource:
    url:jdbc:h2:mem:bookstore_dev
    driverClassName:org.h2.Driver
    username:sa
    password:sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql:true
  h2:
    console:
      enabled:true

logging:
  level:
    com:
      hugovallada: DEBUG