spring:
  datasource:
    url:jdbc:h2:mem:bookstore_prod
    username:sa
    password:sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql:false
  h2:
    console:
      enabled:false

logging:
  level:
    com:
      hugovallada: INFO